### ISSUE TITLE
Only roulette after sub, posted once for every gifted sub

### ISSUE THREAD

**Issue by Fawcan** [pajbot/pajbot2#111]
If a person gifts 5 subscriptions the bot will post 5 times that Roulette is allowed for the next X seconds.
This only happens if the checkbox _Only allow roulettes after sub_ is on.

[Example](https://i.imgur.com/mp80Gg1.png)

**Comment by RAnders00** [comment]
This is a pajbot1 feature, I have moved your issue ticket to there (see the link above this comment).
