### ISSUE TITLE
Ability to enable/disable banphrases

### ISSUE THREAD

**Issue by Mr0ll3** [pajbot/pajbot2#528]
We can currently add and delete ban phrases in the ban phrase list by command.

https://pajlada.pajbot.com/commands/add_banphrase
https://pajlada.pajbot.com/commands/remove_banphrase

You can delete a ban phrase by ID or name and it would be nice if we could use same system to enable and disable ban phrases.

If you have a long list of ban phrases it can be difficult to find the phrase you want to enable temporarily and if it was a recent one you added you need to wait for a long time (30-60s) for the page to load in the ban phrases, before you can navigate the page smoothly and be able to scroll to the bottom.

Quickly enabling ban phrases by ID or name would solve these things.

**Comment by ALazyMeme** [comment]
Since pajbot2 doesn't have a banphrase system with a GUI, I'll assume you're referring to [pajbot1](https://github.com/pajbot/pajbot/).

Once I eventually begin the banphrase refactoring, this will be covered under this issue: https://github.com/pajbot/pajbot/issues/1178
