### ISSUE TITLE
Use PostgreSQL

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot2#56]
postgresql just makes more sense because its moderner and feature-richer. Also no stupid dealing with column size limits and no UTF-8 fiddling.

Also some parts of the bot could be improved due to the usage of postgresql, for example in the reports system - having the DB generate the new report index and returning it from the query instead of keeping the latest ID in bot memory.

**Comment by pajlada** [comment]
agreed, this is something I would like. considering how young the project is, I'm perfectly fine with switching my database stack around (it's not like it's the first time)

**Comment by RAnders00** [comment]
This has been added/changed by https://github.com/pajbot/pajbot2/pull/64
