### ISSUE TITLE
Executing ban action should perform timeout -> delayed ban

### ISSUE THREAD

**Issue by RAnders00** [pajbot/pajbot2#58]
Because you can't double ban like you can double timeout to ensure a timeout properly shows for all web chat users, the bot should do a timeout of some length (e.g. 30 seconds like pajbot1 did seems adequate) and then with a delay perform the permanent ban.

**Comment by alazymeme** [comment]
Is this issue to cater to webchat mods or just regular users?

**Comment by RAnders00** [comment]
Regular users
