### ISSUE TITLE
Early-out when attempting to report already permabanned users 

### ISSUE THREAD

**Issue by zneix** [pajbot/pajbot2#752]
I think it's pointless to report someone, who's already permad from some chat. Yet I caught myself reporting some bad actors for the second time after they've already been banned due to a previous report.

On the other side maybe someone would want to report an already banned person (some sort of ban appeal?). Not sure, but I think this wouldn't make much sense and it's safe to reject reports in these cases.

**Comment by ALazyMeme** [comment]
Duplicate of https://github.com/pajbot/pajbot2/issues/649
