### ISSUE TITLE
Migrate IRC commands to Helix

### ISSUE THREAD

**Issue by Felanbird** [pajbot/pajbot2#817]
cc: pajbot/pajbot#2117

In the context of pajbot2, all available pb2 exec commands are being deprecated via IRC, and will require migration to helix
https://github.com/pajbot/pajbot2/blob/c767e264b57755f83fd1c7bbb5b54797bc5e170c/pkg/modules/debug.go#L64-L83

The report system will also require moving timeout and ban commands to Helix, but I assume that will end up getting covered either way.

**Comment by pajlada** [comment]
Closing in favour of the individually opened issues
